<?php

namespace App\Feeds\Vendors\RCH;

use App\Feeds\Feed\FeedItem;
use App\Feeds\Processor\HttpProcessor;
use App\Feeds\Utils\Data;
use App\Feeds\Utils\Link;

class Vendor extends HttpProcessor
{
    public const CATEGORY_LINK_CSS_SELECTORS = [
        'div.category-top-filter nav.pagination ul.pagination-list li.pagination-item a.pagination-link',
        'ul.nav-bar-ul li a',
        'ul.navList li.navList-item div.cat-wrapper a.navList-action',
        'ul.navList-SubCat li.navList-item .cat-wrapper .cat-name a.navList-action'
    ];
    public const PRODUCT_LINK_CSS_SELECTORS = [ 'li.product article.card figure.card-figure a:first-child' ];

    protected array $first = [
        'https://rchobbyexplosion.com/rc-parts/',
        'https://rchobbyexplosion.com/clearance-specials/',
        'https://rchobbyexplosion.com/rc-batteries/',
        'https://rchobbyexplosion.com/rc-battery-chargers/',
        'https://rchobbyexplosion.com/rc-radio-systems/',
        'https://rchobbyexplosion.com/fun-toy-grade-rc/'
        // 'https://rchobbyexplosion.com/discount-remote-control-trucks/',
        // 'https://rchobbyexplosion.com/discount-remote-control-cars/',
        // 'https://rchobbyexplosion.com/discount-remote-control-drones-helicopters/',
        // 'https://rchobbyexplosion.com/electric-remote-control-boats/',
        // 'https://rchobbyexplosion.com/electric-remote-control-airplanes/',
        // 'https://rchobbyexplosion.com/rc-batteries/',
        // 'https://rchobbyexplosion.com/dhk-hobby-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/atomik-boat-parts/',
        // 'https://rchobbyexplosion.com/atomik-motorcycle-parts/',
        // 'https://rchobbyexplosion.com/atomik/atomik-rc-parts/atomik-motorcycle-parts/atomik-brian-deegan-mm-450-dirtbike-parts/',
        // 'https://rchobbyexplosion.com/udi-rc-parts/',
        // 'https://rchobbyexplosion.com/atomik-rc-parts/',
        // 'https://rchobbyexplosion.com/traxxas-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/team-corally/team-corally-rc-parts/',
        // 'https://rchobbyexplosion.com/pro-line-rc-accessories/',
        // 'https://rchobbyexplosion.com/maverick/maverick-r-c-parts/',
        // 'https://rchobbyexplosion.com/carisma-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/cen-racing-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/align-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/extreme-flyers-rc-parts/',
        // 'https://rchobbyexplosion.com/hobby-people-parts/',
        // 'https://rchobbyexplosion.com/hot-racing-parts/',
        // 'https://rchobbyexplosion.com/hubsan-rc-parts/',
        // 'https://rchobbyexplosion.com/g-made-sawback-parts/',
        // 'https://rchobbyexplosion.com/megatech-rc-parts/',
        // 'https://rchobbyexplosion.com/rage-rc-parts/',
        // 'https://rchobbyexplosion.com/robinson-racing-rc-products/',
        // 'https://rchobbyexplosion.com/rpm-rc-products/',
        // 'https://rchobbyexplosion.com/steerix-rc-parts/',
        // 'https://rchobbyexplosion.com/steerix-rocker-f1-boat-parts/',
        // 'https://rchobbyexplosion.com/st-racing-concepts/',
        // 'https://rchobbyexplosion.com/drone-accessories/',
        // 'https://rchobbyexplosion.com/essential-extras-and-parts/',
        // 'https://rchobbyexplosion.com/venom-airplane-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-airplane-parts/park-fighters-a6m-zero-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-airplane-parts/park-fighters-p-51d-mustang-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-airplane-parts/venom-f-86-desert-rat-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-airplane-parts/venom-f-86-huff-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-airplane-parts/venom-f-86-skyblazer-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-airplane-parts/venom-island-hopper-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-airplane-parts/venom-micro-jet-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-airplane-parts/venom-tradewind-parts/',
        // 'https://rchobbyexplosion.com/venom-axial-ax10-scorpion-upgrades/',
        // 'https://rchobbyexplosion.com/venom-boat-parts/',
        // 'https://rchobbyexplosion.com/venom-hardware-parts/',
        // 'https://rchobbyexplosion.com/venom-helicopter-parts/',
        // 'https://rchobbyexplosion.com/10th-scale-trucks/',
        // 'https://rchobbyexplosion.com/16th-and-18th-scale-trucks/',
        // 'https://rchobbyexplosion.com/8th-scale-trucks/',
        // 'https://rchobbyexplosion.com/remote-control-buggies/',
        // 'https://rchobbyexplosion.com/dhk-trucks/',
        // 'https://rchobbyexplosion.com/kits-build-assemble/',
        // 'https://rchobbyexplosion.com/remote-control-monster-trucks/',
        // 'https://rchobbyexplosion.com/remote-control-rock-crawlers/',
        // 'https://rchobbyexplosion.com/remote-control-short-course-trucks/',
        // 'https://rchobbyexplosion.com/traxxas-trucks/',
        // 'https://rchobbyexplosion.com/remote-control-trucks/unique-rc/',
        // 'https://rchobbyexplosion.com/venom-motorcycle-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-motorcycle-parts/venom-gpv-1-motorcycle-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-motorcycle-parts/venom-vmx-450-dirtbike-parts/',
        // 'https://rchobbyexplosion.com/venom-rock-crawler-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-rock-crawler-parts/venom-creeper-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-rock-crawler-parts/venom-safari-creeper-parts/',
        // 'https://rchobbyexplosion.com/venom-truck-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-truck-parts/venom-gambler-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-boat-parts/electric-king-of-shaves-c1-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-boat-parts/electric-king-of-shaves-p1-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-boat-parts/electric-segad-c1-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-boat-parts/electric-strait-jacket-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-boat-parts/killer-vee-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-boat-parts/king-of-shaves-c1-gas-boat-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-boat-parts/king-of-shaves-p1-gas-boat-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-boat-parts/miss-excite-hydro-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-boat-parts/segad-gas-boat-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-boat-parts/strait-jacket-xl-gas-boat-parts/',
        // 'https://rchobbyexplosion.com/venom/venom-rc-parts/venom-boat-parts/wave-jumper-parts/',
        // 'https://rchobbyexplosion.com/st-racing-bandit-parts/',
        // 'https://rchobbyexplosion.com/st-racing-bigfoot-10th-parts/',
        // 'https://rchobbyexplosion.com/st-racing-e-revo-parts/',
        // 'https://rchobbyexplosion.com/st-racing-maxx-parts/',
        // 'https://rchobbyexplosion.com/st-racing-mini-16th-slash__e-revo-parts/',
        // 'https://rchobbyexplosion.com/st-racing-mini-16th-rally-parts/',
        // 'https://rchobbyexplosion.com/st-racing-traxxas-nitro-slash-parts/',
        // 'https://rchobbyexplosion.com/st-racing-rally-4wd-parts/',
        // 'https://rchobbyexplosion.com/st-racing-revo-3__3-parts/',
        // 'https://rchobbyexplosion.com/st-racing-rustler-parts/',
        // 'https://rchobbyexplosion.com/st-racing-slash-2wd-parts/',
        // 'https://rchobbyexplosion.com/st-racing-slash-4x4-parts/',
        // 'https://rchobbyexplosion.com/st-racing-slayer-parts/',
        // 'https://rchobbyexplosion.com/st-racing-stampede-4x4-parts/',
        // 'https://rchobbyexplosion.com/st-racing-stampede-parts/',
        // 'https://rchobbyexplosion.com/st-racing-summit-parts/',
        // 'https://rchobbyexplosion.com/st-racing-traxxas-monster-jam-parts/',
        // 'https://rchobbyexplosion.com/st-racing-trx-4-parts/',
        // 'https://rchobbyexplosion.com/megatech-airplane-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-a7-tornado-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-airship-1-area-51-blimp-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-airstrike-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-ambassador-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-avion-biplane-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-avion-io-biplane-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-b3-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-cc-flyer-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-fantail-flyer-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-cosmic-flyer-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-firefly-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-freedom-flyer-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-hydro-fly-2-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-megastealth-ii-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-night-flyer-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-hydro-fly-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-nitro-airstrike-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-nitro-capitol-flyer-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-nitro-skyliner-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-party-blimp-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-prowler-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-sky-vector-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-wright-flyer-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-airplane-parts/megatech-x-ec-diversion-parts/',
        // 'https://rchobbyexplosion.com/megatech-boat-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-boat-parts/megatech-caribbean-cruiser-2-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-boat-parts/megatech-h2o-elite-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-boat-parts/megatech-h2o-pro-racer-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-boat-parts/megatech-nirvana-ii-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-boat-parts/megatech-nitro-wicked-angel-parts/',
        // 'https://rchobbyexplosion.com/megatech-car-____-vehicle-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-car-vehicle-parts/mega-missile-launcher-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-car-vehicle-parts/megastorm-hovercraft-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-car-vehicle-parts/megatech-afterburner-nitro-funny-car-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-car-vehicle-parts/megatech-dark-thunder-nitro-dragster-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-car-vehicle-parts/megatech-megapro-pro-pulse-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-car-vehicle-parts/megatech-nitro-razor-xt-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-car-vehicle-parts/megatech-nitro-tempest-gladiator-monster-truck/',
        // 'https://rchobbyexplosion.com/megatech-helicopter-parts/',
        // 'https://rchobbyexplosion.com/chopper-1-fire-medevac-sky-trooper-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-helicopter-parts/mantis-whirlwind-3000-real-world-heli-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-helicopter-parts/megatech-hopper-fly-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-helicopter-parts/megatech-horse-fly-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-helicopter-parts/megatech-housefly-2-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-helicopter-parts/megatech-housefly-unlimited-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-helicopter-parts/megatech-megachopper-ii-parts/',
        // 'https://rchobbyexplosion.com/megatech/megatech-rc-parts/megatech-helicopter-parts/megatech-micro-fly-parts/',
        // 'https://rchobbyexplosion.com/atomik-truck-and-car-parts/',
        // 'https://rchobbyexplosion.com/clearance-specials/',
        // 'https://rchobbyexplosion.com/rc-batteries/alkaline-batteries/',
        // 'https://rchobbyexplosion.com/high-performance-7.4V-2S-lipo-rc-batteries/',
        // 'https://rchobbyexplosion.com/high-performance-11.1v-3s-lipo-rc-batteries/',
        // 'https://rchobbyexplosion.com/high-performance-4s-or-greater-lipo-rc-batteries/',
        // 'https://rchobbyexplosion.com/rc-batteries/lipo-rc-batteries/',
        // 'https://rchobbyexplosion.com/rc-batteries/nicd-rc-batteries/',
        // 'https://rchobbyexplosion.com/rc-batteries/nimh-rc-batteries/',
        // 'https://rchobbyexplosion.com/high-performance-6-cell-or-less-nimh-batteries/',
        // 'https://rchobbyexplosion.com/high-performance-7-cell-nimh-batteries/',
        // 'https://rchobbyexplosion.com/rc-battery-chargers/',
        // 'https://rchobbyexplosion.com/rc-battery-chargers/a-c-wall-chargers/',
        // 'https://rchobbyexplosion.com/rc-battery-chargers/lipo-balance-chargers/',
        // 'https://rchobbyexplosion.com/rc-battery-chargers/multi-function-chargers/',
        // 'https://rchobbyexplosion.com/rc-radio-systems/',
        // 'https://rchobbyexplosion.com/rc-radio-systems/air-rc-radio-systems/',
        // 'https://rchobbyexplosion.com/rc-radio-systems/rc-radio-system-receivers/',
        // 'https://rchobbyexplosion.com/rc-radio-systems/surface-rc-radio-systems/',
        // 'https://rchobbyexplosion.com/fun-toy-grade-rc/',
        // 'https://rchobbyexplosion.com/dhk-cage-r-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/dhk-crosse-brushless-truck-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/dhk-crosse-truck-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/dhk-h119-__21-nitro-engine-parts/',
        // 'https://rchobbyexplosion.com/dhk-hunter-sct-brushless-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/dhk-hunter-sct-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/dhk-maximus-brushless-monster-truck-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/dhk-maximus-nitro-monster-truck-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/dhk-optimus-3s-brushless-buggy-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/dhk-optimus-4s-brushless-buggy-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/dhk-optimus-nitro-buggy-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/dhk-raz-r-2-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/dhk-raz-r-brushless-truck-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/dhk-raz-r-truck-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/dhk-shogun-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/dhk-sportra-sedan-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/dhk-wolf-2-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/dhk-wolf-brushless-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/dhk-wolf-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/dhk-zombie-8e-brushless-truck-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/align-t-rex-100s-parts/',
        // 'https://rchobbyexplosion.com/align-t-rex-100x-parts/',
        // 'https://rchobbyexplosion.com/hot-racing-arrma-parts/',
        // 'https://rchobbyexplosion.com/hot-racing-axial-ax-10-parts/',
        // 'https://rchobbyexplosion.com/hot-racing-axial-scx10-parts/',
        // 'https://rchobbyexplosion.com/hot-racing-traxxas-16th-scale-parts/',
        // 'https://rchobbyexplosion.com/hot-racing-traxxas-e-maxx-parts/',
        // 'https://rchobbyexplosion.com/hot-racing-traxxas-e-revo-parts/',
        // 'https://rchobbyexplosion.com/hot-racing-traxxas-maxx-4s-parts/',
        // 'https://rchobbyexplosion.com/hot-racing-traxxas-slash-stampede-parts/',
        // 'https://rchobbyexplosion.com/hot-racing-traxxas-trx-4-parts/',
        // 'https://rchobbyexplosion.com/hot-racing-traxxas-x-maxx-parts/',
        // 'https://rchobbyexplosion.com/hot-racing-traxxas-xo-1-supercar-parts/',
        // 'https://rchobbyexplosion.com/hot-racing-traxxas-spartan-and-m41-boat-parts/',
        // 'https://rchobbyexplosion.com/hot-racing-traxxas-unlimited-desert-racer-parts/',
        // 'https://rchobbyexplosion.com/axial-yeti-parts/',
        // 'https://rchobbyexplosion.com/robinson-racing-traxxas-16th-revo-and-summit-parts/',
        // 'https://rchobbyexplosion.com/traxxas-e-maxx-parts/',
        // 'https://rchobbyexplosion.com/traxxas-e-revo-brushless-parts/',
        // 'https://rchobbyexplosion.com/traxxas-revo-3__3-parts/',
        // 'https://rchobbyexplosion.com/traxxas-slash-2wd-4x4-parts/',
        // 'https://rchobbyexplosion.com/traxxas-t-maxx-3__3-parts/',
        // 'https://rchobbyexplosion.com/traxxas-electric-vehicle-parts/',
        // 'https://rchobbyexplosion.com/traxxas/traxxas-parts/electric-vehicle-parts/1-10-rally-vxl-parts/body-chassis-attachments/',
        // 'https://rchobbyexplosion.com/traxxas/traxxas-parts/electric-vehicle-parts/1-10-rally-vxl-parts/driveline-steering/',
        // 'https://rchobbyexplosion.com/traxxas/traxxas-parts/electric-vehicle-parts/1-10-rally-vxl-parts/hardware-accessories/',
        // 'https://rchobbyexplosion.com/traxxas/traxxas-parts/electric-vehicle-parts/1-10-rally-vxl-parts/motors-electronics/',
        // 'https://rchobbyexplosion.com/traxxas/traxxas-parts/electric-vehicle-parts/1-10-rally-vxl-parts/suspension-parts/',
        // 'https://rchobbyexplosion.com/traxxas/traxxas-parts/electric-vehicle-parts/1-10-rally-vxl-parts/telemetry-components/',
        // 'https://rchobbyexplosion.com/traxxas/traxxas-parts/electric-vehicle-parts/1-10-rally-vxl-parts/tires-wheels/',
        // 'https://rchobbyexplosion.com/traxxas/traxxas-parts/electric-vehicle-parts/1-10-rally-vxl-parts/transmission-gearing/',
        // 'https://rchobbyexplosion.com/rc-parts-department/pro-line-parts/',
        // 'https://rchobbyexplosion.com/carisma-car-parts/',
        // 'https://rchobbyexplosion.com/extreme-flyer-parts/',
        // 'https://rchobbyexplosion.com/phase-3-parts-and-upgrades/',
        // 'https://rchobbyexplosion.com/rpm-parts/',
        // 'https://rchobbyexplosion.com/udi-rc-parts/',
        // 'https://rchobbyexplosion.com/team-corally-rc-parts/',
        // 'https://rchobbyexplosion.com/rc-parts-department/maverick-parts/',
        // 'https://rchobbyexplosion.com/rc-parts-department/cen-racing-parts/',
        // 'https://rchobbyexplosion.com/gmade-parts/',
        // 'https://rchobbyexplosion.com/rc-parts-department/rage-r-c-parts/',
        // 'https://rchobbyexplosion.com/venom-parts/'
    ];

    public function isValidFeedItem( FeedItem $fi ): bool
    {
        return !empty( $fi->getMpn() ) && !empty( $fi->getImages() );
    }
}